# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-one"
  friendly_name: "AG One"
  config_version: 2.0.5
  name_add_mac_suffix: "false"  # Must have quotes around value
  ag_esphome_config_version: config_version
  friendly_devicename: friendly_name

# Enable Home Assistant API
api:  # Add encryption key as desired

ota:
  - platform: esphome
    password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_not_ssid
  password: !secret wifi_not_password
  manual_ip:
      static_ip: !secret ag_one_ip
      gateway: !secret wifi_not_gateway
      subnet: !secret wifi_not_subnet
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret esphome_fallback_password


dashboard_import:
  package_import_url: github://rkuijer/airgradient_esphome/airgradient-one.yaml
  import_full_config: false

packages:
  board:              github://rkuijer/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  pm_2.5:             github://rkuijer/airgradient_esphome/packages/sensor_pms5003.yaml
  co2:                github://rkuijer/airgradient_esphome/packages/sensor_s8.yaml
  temp_humidity:      github://rkuijer/airgradient_esphome/packages/sensor_sht40.yaml
  tvoc:               github://rkuijer/airgradient_esphome/packages/sensor_sgp41.yaml
  display:            github://rkuijer/airgradient_esphome/packages/display_sh1106_multi_page.yaml
  led:                github://rkuijer/airgradient_esphome/packages/led.yaml
  led_co2:            github://rkuijer/airgradient_esphome/packages/led_co2.yaml
  airgradient_api:    github://rkuijer/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog:  github://rkuijer/airgradient_esphome/packages/watchdog.yaml
  config_button:      github://rkuijer/airgradient_esphome/packages/config_button.yaml
  wifi:               github://rkuijer/airgradient_esphome/packages/sensor_wifi.yaml
  uptime:             github://rkuijer/airgradient_esphome/packages/sensor_uptime.yaml
  safe_mode:          github://rkuijer/airgradient_esphome/packages/switch_safe_mode.yaml
  mics_4514:          github://rkuijer/airgradient_esphome/packages/sensor_mics_4514.yaml
  

binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true  # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
